[package]
name = "jdb_sst_read"
version = "0.1.0"
edition = "2024"
license = "MulanPSL-2.0"
repository = "https://github.com/js0/jdb.git"
homepage = "https://github.com/js0/jdb/tree/main/jdb_sst_read"
description = "jdb_sst_read"
keywords = []
categories = []
readme = "README.md"

[features]
default = []

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
async-stream = "0.3.6"
bitcode = "0.6.9"
compio = { version = "0.17.0", features = ["runtime", "io"] }
crc32fast = "1.5.0"
futures-core = "0.3.31"
gxhash = "3.5.0"
jdb_base = { version = "0.1.1", path = "../jdb_base" }
jdb_fs = { version = "0.1.1", path = "../jdb_fs" }
jdb_pgm = { version = "0.3.10", path = "../jdb_pgm", features = ["bitcode", "key_to_u64"] }
jdb_sst = { version = "0.1.0", path = "../jdb_sst" }
jdb_xorf = { version = "0.12.0", path = "../jdb_xorf", features = ["bitcode"] }
zerocopy = "0.8.33"

[dev-dependencies]
aok = "0.1.18"
compio = { version = "0.17.0", features = ["macros"] }
log = "0.4.29"
log_init = "0.1.34"
static_init = "1.0.4"
