[workspace]
resolver = "2"
members = [
  "jdb",
  "jdb_alloc",
  "jdb_api",
  "jdb_comm", "jdb_compress", "jdb_filter",
  "jdb_fs",
  "jdb_index",
  "jdb_layout", "jdb_meta",
  "jdb_page",
  "jdb_sub",
  "jdb_trait",
  "jdb_vlog",
]
exclude = ["sh/_tmpl"]

[profile.release]
lto = true
opt-level = 3
incremental = true
codegen-units = 1
overflow-checks = false
debug-assertions = false
# panic = 'abort'
# strip = false

[profile.dev]
split-debuginfo = "unpacked"
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
