[package]
name = "jdb_fs"
version = "0.1.1"
edition = "2024"
license = "MulanPSL-2.0"
repository = "https://github.com/js0-site/jdb.git"
homepage = "https://github.com/js0-site/jdb/tree/main/jdb_fs"
description = "jdb_fs"
keywords = [ "filesystem", "async", "io", "storage", "compio" ]
categories = [ "filesystem", "asynchronous", "database" ]
readme = "README.md"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = [ "--cfg", "docsrs" ]

[features]
default = [ ]

[dependencies]
compio-fs = "0.10.0"
crc32fast = "1.5.0"
memchr = "2.7.6"
fast32 = "1.0.3"
hashlink = "0.11.0"
log = "0.4.29"
futures = "0.3.31"
either = "1.15.0"
zbin = { version = "0.1.4", path = "../zbin" }

[dependencies.compio]
version = "0.17.0"
features = [ "io", "runtime" ]

[dependencies.zerocopy]
version = "0.8.33"
features = [ "derive" ]

[dependencies.jdb_lru]
version = "0.1.4"

[dependencies.jdb_base]
path = "../jdb_base"
version = "0.1.1"

[dev-dependencies]
aok = "0.1.18"
compio-runtime = "0.10.1"
log = "0.4.29"
log_init = "0.1.34"
static_init = "1.0.4"
tempfile = "3.24.0"

[dev-dependencies.compio]
version = "0.17.0"
features = [ "macros" ]
