[package]
name = "xorf-analysis"
version = "0.0.0"
authors = []
publish = false
edition = "2021"
readme = "README.md"

[[bin]]
name = "zeroes"
path = "src/zeroes.rs"

[dependencies]
rand = "0.7.3"
# default-features = false
# features = ["binary-fuse"]
