[package]
name = "jdb_val"
version = "0.1.0"
edition = "2024"
license = "MulanPSL-2.0"
repository = "https://github.com/js0-site/jdb.git"
homepage = "https://github.com/js0-site/jdb/tree/main/jdb_val"
description = "Async WAL Value Storage for KV Separation / 异步 WAL 值存储，用于 KV 分离架构"
keywords = [ "wal", "storage", "kv", "async" ]
categories = [ "database", "asynchronous", "filesystem" ]
readme = "README.md"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = [ "--cfg", "docsrs" ]

[features]
default = [ ]

[dependencies]
crc32fast = "1.5.0"
thiserror = "2.0.17"
compio-fs = "0.10.0"
hashlink = "0.11.0"
log = "0.4.29"
ider = "0.1.1"
futures = "0.3.31"

[dependencies.jdb_base]
path = "../jdb_base"
version = "0.1.1"

[dependencies.jdb_fs]
path = "../jdb_fs"
version = "0.1.1"

[dependencies.jdb_ckp]
path = "../jdb_ckp"
version = "0.1.3"

[dependencies.size_lru]
version = "0.1.26"
path = "../size_lru"
features = [ "lhd", "no" ]

[dependencies.zbin]
path = "../zbin"
version = "0.1.4"

[dependencies.jdb_lru]
path = "../jdb_lru"
version = "0.1.4"

[dependencies.jdb_lock]
path = "../jdb_lock"
version = "0.1.1"

[dependencies.zerocopy]
version = "0.8.31"
features = [ "derive", "simd" ]

[dependencies.compio]
version = "0.17.0"
features = [ "runtime", "io" ]

[dependencies.compio-runtime]
version = "0.10.1"
features = [ "time" ]

[dev-dependencies]
aok = "0.1.18"
log = "0.4.29"
log_init = "0.1.34"
proptest = "1.9.0"
static_init = "1.0.4"
tempfile = "3.24.0"

[dev-dependencies.compio]
version = "0.17.0"
features = [ "macros" ]
