[package]
name = "jdb"
version = "0.1.0"
edition = "2024"
license = "MulanPSL-2.0"
repository = "https://github.com/js0/jdb.git"
description = "JDB - Time-series database kernel"

[[bench]]
name = "perf"
harness = false

[dependencies]
jdb_api = { path = "../jdb_api" }
jdb_comm = { path = "../jdb_comm" }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
tokio = { version = "1.48", features = ["rt", "rt-multi-thread", "macros"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
aok = "0.1.18"
log = "0.4.29"
log_init = "0.1.34"
static_init = "1.0.4"
fastrand = "2.3.0"
