[package]
name = "jdb_sst"
version = "0.1.1"
edition = "2024"
license = "MulanPSL-2.0"
repository = "https://github.com/js0-site/jdb.git"
homepage = "https://github.com/js0-site/jdb/tree/main/jdb_sst"
description = "jdb_sst"
keywords = []
categories = []
readme = "README.md"

[features]
default = []

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
jdb_base = { version = "0.1.0", path = "../jdb_base" }
zerocopy = "0.8.33"
log = "0.4.29"
bitcode = "0.6.9"
jdb_xorf = { version = "0.13.9", features = ["bitcode"] }
jdb_fsst = { version = "0.1.4", path = "../jdb_fsst" }
jdb_pgm = { version = "0.3.14", features = ["bitcode", "key_to_u64"] }

[dev-dependencies]
aok = "0.1.18"
compio = { version = "0.17.0", features = ["macros"] }
log_init = "0.1.34"
static_init = "1.0.4"
