[package]
name = "jdb_sst"
version = "0.1.0"
edition = "2024"
license = "MulanPSL-2.0"
repository = "https://github.com/js0-site/jdb.git"
homepage = "https://github.com/js0-site/jdb/tree/main/jdb_sst"
description = "jdb_sst"
keywords = []
categories = ["database", "structures", "encoding", "filesystem", "compression"]
readme = "README.md"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = []

[dependencies]
futures-core = "0.3.31"
thiserror = "2.0.17"
zerocopy = "0.8.33"

[dependencies.jdb_base]
version = "0.1.1"
path = "../jdb_base"

[dependencies.shared_prefix_len]
version = "0.1.1"

[dev-dependencies]
aok = "0.1.18"
log_init = "0.1.34"
static_init = "1.0.4"
tempfile = "3.24.0"

[dev-dependencies.jdb_mem]
path = "../jdb_mem"
version = "0.1.0"
